# Generated by Django 4.2.3 on 2023-07-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='type',
        ),
        migrations.AddField(
            model_name='todo',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='webapp.type', verbose_name='Тип'),
        ),
    ]
