# Generated by Django 4.2.3 on 2023-07-13 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='projects',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='project', to='webapp.project', verbose_name='Проект'),
        ),
    ]
