# Generated by Django 4.2.3 on 2023-07-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_todo_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='projects',
            new_name='project',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
